name: standard
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  standard:
    uses: bounded-systems/.github/.github/workflows/repo-standard.yml@4f465d0bffbee609309468a541853095aefab6ad
    with:
      security: true
      test: true
      runtime: bun
      test-command: "bun test"
